services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: agentsfun
    volumes:
      - mongo-data:/data/db

  # mailhog:
  #   image: mailhog/mailhog:latest
  #   restart: unless-stopped
  #   ports:
  #     - "1025:1025" # SMTP server
  #     - "8025:8025" # Web UI
  #   environment:
  #     MH_STORAGE: memory
  #     MH_UI_WEB_PATH: mailhog

volumes:
  mongo-data:
